/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("@tailwindcss/aspect-ratio"), require("daisyui")],
  daisyui: {
    styled: false,
    themes: [
      {
        cmyk: {
          "color-scheme": "light",
          primary: "#45AEEE",
          secondary: "#E8488A",
          accent: "#FFF232",
          neutral: "#1a1a1a",
          "base-100": "#ffffff",
          info: "#4AA8C0",
          success: "#823290",
          warning: "#EE8133",
          error: "#E93F33",
          "neutral-content": "#FF0000",
          "primary-content": "#FF0000",
          "base-content": "#FF0000",
        },
        coffee: {
          "color-scheme": "dark",
          primary: "#DB924B",
          secondary: "#263E3F",
          accent: "#10576D",
          neutral: "#162425",
          "base-100": "#20161F",
          "base-content": "#756E63",
          info: "#8DCAC1",
          success: "#9DB787",
          warning: "#FFD25F",
          error: "#FC9581",
          "neutral-content": "#FF0000",
          "primary-content": "#FF0000",
        },
        cupcake: {
          "color-scheme": "light",
          primary: "#65c3c8",
          secondary: "#ef9fbc",
          accent: "#eeaf3a",
          neutral: "#291334",
          "base-100": "#faf7f5",
          "base-200": "#efeae6",
          "base-300": "#e7e2df",
          "base-content": "#291334",
          "neutral-content": "#FF0000",
          "primary-content": "#FF0000",
        },
        dark: {
          "color-scheme": "dark",
          primary: "#661AE6",
          "primary-content": "#ffffff",
          secondary: "#D926AA",
          "secondary-content": "#ffffff",
          accent: "#1FB2A5",
          "accent-content": "#ffffff",
          neutral: "#191D24",
          "neutral-focus": "#111318",
          "neutral-content": "#A6ADBB",
          "base-100": "#2A303C",
          "base-200": "#242933",
          "base-300": "#20252E",
          "base-content": "#A6ADBB",
        },
        light: {
          "color-scheme": "light",
          "accent-content": "#163835",
          "base-100": "#ffffff",
          "base-200": "#F2F2F2",
          "base-300": "#E5E6E6",
          "base-400": "#D5E6E6",
          "base-content": "#1f2937",
          "neutral-content": "#ffffff",
          "primary-content": "#ffffff",
          "secondary-content": "#ffffff",
          accent: "#37cdbe",
          neutral: "#3d4451",
          primary: "#570df8",
          secondary: "#f000b8",
        },
        forest: {
          "color-scheme": "dark",
          primary: "#1eb854",
          "primary-content": "#c2ffd7",
          secondary: "#1fd65f",
          accent: "#d99330",
          neutral: "#110e0e",
          "base-100": "#171212",
          "--rounded-btn": "1.9rem",
          "neutral-content": "#FF0000",
          "base-content": "#FF0000",
        },
        retro: {
          "color-scheme": "light",
          primary: "#ef9995",
          "primary-content": "#282425",
          secondary: "#a4cbb4",
          "secondary-content": "#282425",
          accent: "#ebdc99",
          "accent-content": "#282425",
          neutral: "#7d7259",
          "neutral-content": "#e4d8b4",
          "base-100": "#e4d8b4",
          "base-200": "#d2c59d",
          "base-300": "#c6b386",
          "base-content": "#282425",
          info: "#2563eb",
          success: "#16a34a",
          warning: "#d97706",
          error: "#dc2626",
          "--rounded-box": "0.4rem",
          "--rounded-btn": "0.4rem",
          "--rounded-badge": "0.4rem",
        },
        night: {
          "color-scheme": "dark",
          primary: "#38bdf8",
          secondary: "#818CF8",
          accent: "#F471B5",
          neutral: "#1E293B",
          "neutral-focus": "#273449",
          "base-100": "#0F172A",
          info: "#0CA5E9",
          success: "#2DD4BF",
          warning: "#F4BF50",
          error: "#FB7085",
          "neutral-content": "#FF0000",
          "primary-content": "#FF0000",
          "base-content": "#FF0000",
        },

        winter: {
          "color-scheme": "light",
          primary: "#047AFF",
          secondary: "#463AA2",
          accent: "#C148AC",
          neutral: "#021431",
          "base-100": "#ffffff",
          "base-200": "#F2F7FF",
          "base-300": "#E3E9F4",
          "base-content": "#394E6A",
          info: "#93E7FB",
          success: "#81CFD1",
          warning: "#EFD7BB",
          error: "#E58B8B",
          "neutral-content": "#FF0000",
          "primary-content": "#FF0000",
        },
      },
    ],
  },
};
